# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/vivadoprograms/my_ip/ip_repo/edit_PMOD_SSD_v1_0.cache/wt [current_project]
set_property parent.project_path E:/vivadoprograms/my_ip/ip_repo/edit_PMOD_SSD_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths e:/vivadoprograms/my_ip/ip_repo/PMOD_SSD_1.0 [current_project]
read_verilog -library xil_defaultlib {
  E:/vivadoprograms/my_ip/ip_repo/edit_PMOD_SSD_v1_0.srcs/sources_1/imports/Desktop/column_scan_module.v
  E:/vivadoprograms/my_ip/ip_repo/edit_PMOD_SSD_v1_0.srcs/sources_1/imports/Desktop/row_scan_module.v
  E:/vivadoprograms/my_ip/ip_repo/edit_PMOD_SSD_v1_0.srcs/sources_1/imports/Desktop/number_mod_module.v
  E:/vivadoprograms/my_ip/ip_repo/edit_PMOD_SSD_v1_0.srcs/sources_1/imports/Desktop/SSD_encoder_module.v
  E:/vivadoprograms/my_ip/ip_repo/edit_PMOD_SSD_v1_0.srcs/sources_1/imports/Desktop/SSD_scan_module.v
  E:/vivadoprograms/my_ip/ip_repo/edit_PMOD_SSD_v1_0.srcs/sources_1/imports/Desktop/SSD_top.v
  E:/vivadoprograms/my_ip/ip_repo/PMOD_SSD_1.0/hdl/PMOD_SSD_v1_0_S_AXI.v
  E:/vivadoprograms/my_ip/ip_repo/PMOD_SSD_1.0/hdl/PMOD_SSD_v1_0.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top PMOD_SSD_v1_0 -part xc7z010clg400-1


write_checkpoint -force -noxdef PMOD_SSD_v1_0.dcp

catch { report_utilization -file PMOD_SSD_v1_0_utilization_synth.rpt -pb PMOD_SSD_v1_0_utilization_synth.pb }
